name: Build (develop/release) with latest tag version

on:
  push:
    branches: [develop, release]
  pull_request:
    branches: [develop, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Compute VERSION from latest semver tag v*
        shell: bash
        run: |
          RAW_TAG=$(git tag -l 'v*' | sort -V | tail -n1)
          if [ -z "$RAW_TAG" ]; then RAW_TAG="v0.0.0"; fi
          SUFFIX="-dev+${GITHUB_SHA::7}"
          VERSION="$RAW_TAG$SUFFIX"

          # Mantém VERSION para UI (pode conter '+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BASE_VERSION=$RAW_TAG" >> $GITHUB_ENV

          # Gera DOCKER_TAG seguro: minúsculo e só [a-z0-9._-]
          SAFE_TAG=$(echo "$VERSION" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]/-/g')
          echo "DOCKER_TAG=$SAFE_TAG" >> $GITHUB_ENV

          echo "Computed VERSION=$VERSION"
          echo "Docker tag will be: $SAFE_TAG"

      - name: Build frontend with VERSION
        run: |
          docker build -t frontend-image --build-arg VERSION=${{ env.VERSION }} ./Front

      - name: Build backend with VERSION (opcional; por ora não precisa)
        if: ${{ false }}
        run: |
          docker build -t backend-image --build-arg VERSION=${{ env.VERSION }} ./Back/DockerRemote

      - name: Login no GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag e push frontend para GHCR
        run: |
          docker tag frontend-image ghcr.io/phdguigui/frontend-image:${{ env.DOCKER_TAG }}
          docker push ghcr.io/phdguigui/frontend-image:${{ env.DOCKER_TAG }}
