name: Publish Docker Images on Main

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    # Roda em uma VM Ubuntu gerenciada pelo GitHub
    runs-on: ubuntu-latest

    # DinD - Docker in Docker
    # Permite executar comandos Docker dentro do pipeline
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      # Baixa o código-fonte do repositório na VM do GitHub (para que o pipeline possa acessar os Dockerfiles)
      - name: Checkout código
        uses: actions/checkout@v4

      # Roda o docker-compose para buildar as imagens
      - name: Build containers (frontend e backend)
        run: |
          docker compose build
          docker images

      - name: Login no GHCR
        run: docker login ghcr.io -u phdguigui -p ${{ secrets.GHCR }}

      - name: Tag frontend para GHCR
        run: docker tag frontend-image ghcr.io/phdguigui/frontend-image:latest

      - name: Push frontend para GHCR
        run: docker push ghcr.io/phdguigui/frontend-image:latest

      - name: Tag backend para GHCR
        run: docker tag backend-image ghcr.io/phdguigui/backend-image:latest

      - name: Push backend para GHCR
        run: docker push ghcr.io/phdguigui/backend-image:latest
